### ISSUE TITLE
Update to work with Winston 2.x

### ISSUE THREAD

**Issue by dortamur** [lancespeelmon/winston-syslog-posix#4]
Hi! I'm using Winston 2.1.1, and because of the winston dependency on 1.0.2, installing this via npm installs its own winston, rather than using the main one, and as a result, does not work.

If I copy out the library js file as a local module, it logs to syslog fine, but doesn't call the formatting routines, so just dumps the JSON data.

Can this be updated to work with the newer winston? Or is there any alternative module for posix syslogging with winston 2.x?

Thanks.

**Comment by nytsua** [comment]
I just ran into this issue as well, is this project still active?

**Comment by lancespeelmon** [comment]
winston-syslog-posix@2.0.0 published to npm
