### ISSUE TITLE
Why prepend message with level ?

### ISSUE THREAD

**Issue by cdupetit** [lancespeelmon/winston-syslog-posix#5]
Why do you prepend level in message while you can get it by the property "syslogseverity-text" in the rsyslog config ?
I expect to have the choice in the transport config to prepend or not the message with the level.
It'll be easy to add an option showLevel in the configuration to show it or not (with a default value to true).
Thanks in advance.
Regards

**Comment by lancespeelmon** [comment]
Sounds reasonable. 😺 Would you submit a pull request? Thanks, L
